--CREATE TABLE employees (
--    username TEXT,
--    first_name TEXT,
--    last_name TEXT,
--    birthdate DATE,
--    country TEXT
--);

INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('cnlvhcdw', 'Cameron', 'Orr', '1996-01-24', 'Panama');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('gtqwlqgn', 'Stacey', 'Hughes', '1969-07-05', 'Croatia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('oeibhguu', 'Danny', 'Adams', '1992-08-04', 'Chad');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('eqolsqhi', 'Tammy', 'Mclean', '1990-06-05', 'Georgia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('onjsilpq', 'Kayla', 'Buchanan', '1983-06-10', 'Turkey');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('pzrewhol', 'Chelsea', 'Price', '1987-01-17', 'Brazil');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('cmwtecgq', 'Rebecca', 'King', '1982-06-24', 'Dominica');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mdnzmozw', 'Marcus', 'Simpson', '1963-07-14', 'Australia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('jbkwzhbp', 'Paul', 'Wong', '1974-01-29', 'Rwanda');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('arpfoyto', 'Christopher', 'Hart', '1995-07-09', 'France');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mbnreqgg', 'Yvonne', 'Reese', '1969-02-03', 'British Virgin Islands');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('aicycxiv', 'Frances', 'Rodriguez', '1971-06-26', 'Belarus');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('himdgxpm', 'Matthew', 'Woods', '1989-04-30', 'Saint Barthelemy');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('wpqyjlge', 'John', 'Russell', '1984-02-23', 'Andorra');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('tvamyjyp', 'Stephanie', 'Graves', '1982-05-20', 'Saint Vincent and the Grenadines');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('lfwtddna', 'Diana', 'Snyder', '1999-08-31', 'Ireland');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('egtyvbqt', 'Jacob', 'Gilmore', '1991-06-25', 'Mongolia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ssjzujvb', 'Maria', 'Dodson', '1962-05-29', 'Nigeria');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('loydwpnv', 'Sheila', 'Moore', '1984-07-24', 'Kyrgyz Republic');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('yviahohz', 'Sarah', 'Cole', '1959-01-06', 'Falkland Islands (Malvinas)');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('nucfhayf', 'Carol', 'Martin', '1984-07-06', 'Kiribati');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('oxkisgdc', 'Christopher', 'Turner', '1986-03-31', 'Antarctica (the territory South of 60 deg S)');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('hvzwuqco', 'Melanie', 'Miller', '1975-10-26', 'Brazil');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('kjdcatil', 'Holly', 'Rogers', '1982-11-18', 'Kuwait');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('tppfadvd', 'Melanie', 'Vega', '1992-11-07', 'United States Virgin Islands');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ngvlcgzy', 'Johnny', 'Jones', '2006-06-10', 'Taiwan');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ygvfbooy', 'Jermaine', 'Williams', '1983-05-28', 'Faroe Islands');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ibjlflnn', 'Christopher', 'Bailey', '1967-04-23', 'Cyprus');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ttegybkj', 'Billy', 'Gomez', '1970-02-14', 'Bermuda');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('lhhbmqat', 'Megan', 'Murphy', '1974-02-17', 'Tuvalu');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('bucqxrfr', 'Tonya', 'Turner', '1999-04-16', 'Guam');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('kcnwgfcf', 'Sara', 'Jordan', '1971-05-15', 'Namibia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('zszurtth', 'Shaun', 'Taylor', '1991-03-14', 'San Marino');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('zgfwlgdj', 'Christine', 'Kelly', '1963-03-18', 'Rwanda');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('zoqqjkhb', 'Isaac', 'Gray', '1969-10-08', 'Fiji');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('jtaajwlb', 'Adrian', 'Sanchez', '1962-06-26', 'Armenia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('vdrsmwym', 'Andrew', 'Lopez', '1974-07-21', 'Cook Islands');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('toladtjv', 'Adam', 'Baker', '1998-09-06', 'Tajikistan');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('lvwoazqs', 'Alexis', 'Bennett', '1998-09-14', 'Lebanon');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('yjzkenpm', 'Richard', 'Nunez', '1986-10-13', 'San Marino');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('oncuflnl', 'Tracy', 'Johnson', '1966-03-08', 'Uruguay');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ijhvaeek', 'Michael', 'Johnson', '1985-11-16', 'Ghana');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('lhbrotfz', 'Fernando', 'Norton', '2006-02-14', 'Namibia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mmzpjbrh', 'Steven', 'Garner', '1977-12-09', 'Finland');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mqopxffm', 'Danny', 'Davenport', '1960-06-08', 'Albania');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ibejcuyp', 'Ashley', 'Welch', '1966-10-24', 'Mongolia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('snbmgwtk', 'Hailey', 'Garcia', '1978-03-12', 'Sudan');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mitgcolw', 'Samantha', 'Smith', '1992-04-23', 'Korea');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('gzibjyre', 'William', 'Bautista', '1975-04-03', 'Eritrea');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('wymwmtum', 'Melissa', 'Holt', '2003-04-29', 'Comoros');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('smfnspdb', 'Crystal', 'Hansen', '1975-07-22', 'Colombia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mofauloe', 'Anna', 'Anthony', '1980-12-16', 'Saint Vincent and the Grenadines');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('bfowqtpz', 'Edward', 'Parker', '1985-06-23', 'Brazil');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('esoxcody', 'Sandra', 'Smith', '1989-05-07', 'Antigua and Barbuda');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('unnbvatl', 'Dean', 'Wolfe', '2006-04-24', 'Cambodia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('trfhrcjv', 'Bryce', 'Freeman', '1959-04-19', 'Suriname');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('hrkryzsi', 'Leah', 'Hawkins', '1975-06-18', 'Italy');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('byguekdn', 'Ashley', 'Duran', '1964-04-19', 'Taiwan');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('sxeonwqg', 'Amber', 'Hamilton', '1981-04-13', 'Serbia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('uvyridmc', 'Justin', 'Coleman', '1985-12-24', 'Cocos (Keeling) Islands');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('pqflbwiv', 'Bryan', 'Smith', '1994-01-20', 'Brazil');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('acwbthge', 'Joseph', 'Murphy', '1982-01-11', 'Brunei Darussalam');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('toygqnyg', 'Daniel', 'Garza', '1986-07-10', 'Andorra');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('tzbbnxvb', 'Marcus', 'Singh', '1998-06-04', 'British Indian Ocean Territory (Chagos Archipelago)');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('uvikxblc', 'Jennifer', 'Erickson', '1961-10-14', 'Germany');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('vjwgipus', 'Marc', 'Holmes', '1958-10-03', 'Liechtenstein');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('setpvxyr', 'Anthony', 'Berry', '1990-05-28', 'India');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('gprzpjzz', 'Chelsea', 'Moreno', '1969-10-05', 'Albania');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('udpnosrh', 'Richard', 'Lowe', '1967-12-25', 'Bahamas');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('natxyrae', 'Cheryl', 'Ferguson', '1981-06-04', 'Netherlands Antilles');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('blmvqfdg', 'Lisa', 'Edwards', '1981-02-28', 'Tanzania');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ypspiowh', 'Ryan', 'Ryan', '1969-02-15', 'Nepal');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('vgkfaoiq', 'Deanna', 'Brown', '1974-09-23', 'Hungary');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('hhwemfci', 'Trevor', 'Garcia', '2001-07-25', 'Uruguay');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('nokpvgvp', 'Michael', 'Owens', '1972-04-13', 'Gambia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('isofshwh', 'Brittany', 'Fisher', '1982-01-22', 'Croatia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('fgxqridb', 'Kathleen', 'Spencer', '1961-02-21', 'Switzerland');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('kmidopqk', 'Dawn', 'Alexander', '1981-10-21', 'France');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('nxnozkza', 'Kathy', 'Flowers', '1958-12-26', 'Niue');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('lcudjmlt', 'Robert', 'Turner', '1970-09-30', 'Malaysia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('biwtdofx', 'Evelyn', 'Mitchell', '1962-03-19', 'Micronesia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('amaanash', 'Adrienne', 'Cook', '1974-11-14', 'Burundi');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('csothgyz', 'Bradley', 'Nicholson', '1970-08-16', 'Martinique');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('qbnevwjv', 'Madeline', 'Smith', '1980-01-22', 'Hungary');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('quvrzytg', 'Donald', 'Tran', '1968-05-22', 'Jamaica');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('whyigwpb', 'Miranda', 'Herrera', '1976-10-03', 'Moldova');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('wuvboolm', 'Janice', 'Irwin', '1989-12-03', 'Jordan');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('nwgpwxxh', 'Alexander', 'Byrd', '1975-12-11', 'Bulgaria');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('anpcjptn', 'Timothy', 'Wilson', '1982-08-08', 'Morocco');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('crydfcvu', 'Donna', 'Brown', '1977-06-02', 'France');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mcfwvpcb', 'Valerie', 'Nguyen', '1998-08-19', 'Indonesia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('husmaynp', 'Alejandro', 'Decker', '1972-02-25', 'Liberia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('mzkjfstz', 'Catherine', 'Jenkins', '1998-12-19', 'Congo');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('kgarzjpz', 'Marilyn', 'Hanson', '2004-03-26', 'Algeria');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('ttfgznqg', 'Tiffany', 'Hernandez', '1983-04-27', 'French Southern Territories');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('fbbmgbeq', 'Russell', 'Thornton', '1993-12-11', 'Cote d'Ivoire');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('uffxnkml', 'Todd', 'Garrison', '1995-08-01', 'Gambia');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('pjavmmze', 'Melanie', 'Buchanan', '1971-12-05', 'Taiwan');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('bnxofven', 'Michael', 'Dean', '1989-11-11', 'Vanuatu');
INSERT INTO employees (username, first_name, last_name, birthdate, country) VALUES ('qvwigcod', 'Roberto', 'Green', '1960-03-05', 'Suriname');

